CREATE TABLE GENIE_USER (
    user_Id varchar(25),
    mdm_Id varchar(25),
    cust_Id varchar(25),
    mobile_No varchar(25),
    pan_No varchar(25),
    customer_Name varchar(25),
    occupation varchar(25),
    gender varchar(25),
    acc_no  varchar(25),
    ckyc_No varchar(25),
    upi varchar(25),
    email varchar(25),
    twitter_Handle varchar(25),
    dob varchar(25),
    address_City varchar(25),
    address_Area varchar(25),
    home_Branch varchar(25),
    asset_RM varchar(25),
    liability_RM varchar(25),
    group_Id varchar(25),
    business_Segment varchar(25),
    partner_Segment varchar(25),
    cust_Open_Date  varchar(25),
    PRIMARY KEY (cust_Id)
);